### ISSUE TITLE
The C13 described samples in the metadata are give SSW__glc IDs

### ISSUE THREAD

**Issue by pvphaneuf** [SBRG/precise-db#2]
The metadata has the following:
ssw__glc_ale1__1 = Escherichia coli C13.1.133.1
ssw__glc_ale2__1 = Escherichia coli C13.1.134.1
ssw__glc_ale3__1 = Escherichia coli C13.6.133.1

Seems like these C13 samples should be associated with a "C13" project, or the "Strain Description" may have a typo where "SSW" was meant instead of "C13".

2 of the samples used also are representing the same ALE: C13 ALE1.

**Comment by avsastry** [comment]
I kept the project as SSW because they were also reported in the SSW paper as the Glucose ALE RNA-seq data. They also share the same GEO accession ID as the rest of the SSW paper.

As for the two samples from the same ALE, they seem to have mutually exclusive mutations even though they're only one flask apart. They're clonal isolates though, so perhaps the ALE had a few sub-populations.

**Comment by pvphaneuf** [comment]
makes sense
