### ISSUE TITLE
Negative values in data passed to %s" % whom

### ISSUE THREAD

**Issue by sotuamax** [SBRG/precise-db#5]
Hi,

I run the script using your example dataset, and it works well. But when I use my own data and run the same pipeline, there is an error occurred in "cluster_components.py" step. The error output like this:

<img width="890" alt="Screen Shot 2020-04-19 at 12 38 44 PM" src="https://user-images.githubusercontent.com/63678158/79696590-ba16ec80-823a-11ea-8cfe-298e4978904a.png">

I checked the distance matrix by writing it to a new file. Both the example and my distance matrix have some negative values. How to explain and figure out the error? Can anybody give a hand?

Thanks in advance.

**Comment by sotuamax** [comment]
D = sparse.csr_matrix((1-D.data,D.indices,D.indptr)) 
# I just write the D object out to check the distance array.

**Comment by avsastry** [comment]
I checked the values and the maximum value of D.data was only 1e-5 above 1 due to rounding errors. When I fixed this by rounding numbers between 1 and 1.00001 to 1, another error came up from DBSCAN.

I realized that the new version of scikit-learn (0.22.1) may have some bugs in DBSCAN, so I reverted back to 0.20.3, and it worked fine (even without rounding). Try running the code in the conda environment uploaded in https://github.com/SBRG/precise-db/commit/abe66d0078eab28ed3fce11e4838382a4cf112fb: https://github.com/SBRG/precise-db/blob/master/scripts/environment.yml
